//! Sole declarative registries for process options and live meta commands.

use clap::{Arg, ArgAction, Command, ValueHint};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OptionId {
    Command,
    File,
    Parameter,
    ParametersFile,
    Init,
    Format,
    Output,
    Force,
    Header,
    Timing,
    Progress,
    Color,
    NullToken,
    KeepGoing,
    Config,
    History,
    Quiet,
    Help,
    Version,
    Rows,
    Width,
    NullDisplay,
    Multiline,
    Highlight,
    Completion,
    HistoryLimit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OptionValueKind {
    Flag,
    Text,
    Path,
    Choice,
    PositiveInteger,
    RepeatableText,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OptionScope {
    Invocation,
    Display,
    Editor,
}

#[derive(Debug, Clone, Copy)]
pub struct OptionSpec {
    pub id: OptionId,
    pub clap_id: &'static str,
    pub short: Option<char>,
    pub long: Option<&'static str>,
    pub negative_id: Option<&'static str>,
    pub negative_long: Option<&'static str>,
    pub value_name: Option<&'static str>,
    pub value_kind: OptionValueKind,
    pub accepted: &'static [&'static str],
    pub default: Option<&'static str>,
    pub config_key: Option<&'static str>,
    pub scope: OptionScope,
    pub interactive: bool,
    pub help: &'static str,
}

const FORMATS: &[&str] = &[
    "auto", "box", "table", "csv", "tsv", "json", "jsonl", "markdown", "line", "trash",
];
const AUTO_ON_OFF: &[&str] = &["auto", "on", "off"];
const COLORS: &[&str] = &["auto", "always", "never"];
const WIDTHS: &[&str] = &["auto", "positive integer"];
const ROWS: &[&str] = &["all", "default", "positive integer"];
const NULL_DISPLAY: &[&str] = &["literal", "empty"];
const BOOL: &[&str] = &["true", "false"];

pub static OPTION_REGISTRY: &[OptionSpec] = &[
    option(
        OptionId::Command,
        "command",
        Some('c'),
        Some("command"),
        None,
        None,
        Some("CYPHER"),
        OptionValueKind::Text,
        &[],
        None,
        None,
        OptionScope::Invocation,
        false,
        "Execute one command string",
    ),
    option(
        OptionId::File,
        "file",
        Some('f'),
        Some("file"),
        None,
        None,
        Some("PATH"),
        OptionValueKind::Path,
        &[],
        None,
        None,
        OptionScope::Invocation,
        false,
        "Execute one UTF-8 command file",
    ),
    option(
        OptionId::Parameter,
        "param",
        None,
        Some("param"),
        None,
        None,
        Some("NAME=JSON"),
        OptionValueKind::RepeatableText,
        &[],
        None,
        None,
        OptionScope::Invocation,
        true,
        "Bind a repeatable query parameter",
    ),
    option(
        OptionId::ParametersFile,
        "params-file",
        None,
        Some("params-file"),
        None,
        None,
        Some("PATH"),
        OptionValueKind::Path,
        &[],
        None,
        None,
        OptionScope::Invocation,
        false,
        "Load parameters from one JSON object",
    ),
    option(
        OptionId::Init,
        "init",
        Some('i'),
        Some("init"),
        None,
        None,
        Some("PATH"),
        OptionValueKind::Path,
        &[],
        None,
        None,
        OptionScope::Invocation,
        false,
        "Execute an explicit initialization file",
    ),
    option(
        OptionId::Format,
        "format",
        None,
        Some("format"),
        None,
        None,
        Some("FORMAT"),
        OptionValueKind::Choice,
        FORMATS,
        Some("auto"),
        Some("format"),
        OptionScope::Display,
        true,
        "Select automatic or explicit result format",
    ),
    option(
        OptionId::Output,
        "output",
        Some('o'),
        Some("output"),
        None,
        None,
        Some("PATH"),
        OptionValueKind::Path,
        &[],
        None,
        None,
        OptionScope::Invocation,
        true,
        "Write result data to a file",
    ),
    option(
        OptionId::Force,
        "force",
        None,
        Some("force"),
        None,
        None,
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("false"),
        None,
        OptionScope::Invocation,
        false,
        "Permit replacement of an existing output file",
    ),
    option(
        OptionId::Header,
        "header",
        None,
        Some("header"),
        Some("no-header"),
        Some("no-header"),
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("true"),
        None,
        OptionScope::Display,
        false,
        "Control CSV and TSV headers",
    ),
    option(
        OptionId::Timing,
        "timing",
        None,
        Some("timing"),
        Some("no-timing"),
        Some("no-timing"),
        None,
        OptionValueKind::Flag,
        BOOL,
        None,
        Some("timing"),
        OptionScope::Display,
        true,
        "Control timing summaries",
    ),
    option(
        OptionId::Progress,
        "progress",
        None,
        Some("progress"),
        None,
        None,
        Some("WHEN"),
        OptionValueKind::Choice,
        AUTO_ON_OFF,
        Some("auto"),
        Some("progress"),
        OptionScope::Display,
        true,
        "Control live progress",
    ),
    option(
        OptionId::Color,
        "color",
        None,
        Some("color"),
        None,
        None,
        Some("WHEN"),
        OptionValueKind::Choice,
        COLORS,
        Some("auto"),
        Some("color"),
        OptionScope::Display,
        false,
        "Control ANSI styling",
    ),
    option(
        OptionId::NullToken,
        "null",
        None,
        Some("null"),
        None,
        None,
        Some("TOKEN"),
        OptionValueKind::Text,
        &[],
        Some("\\N"),
        None,
        OptionScope::Display,
        true,
        "Select the CSV and TSV NULL token",
    ),
    option(
        OptionId::KeepGoing,
        "keep-going",
        None,
        Some("keep-going"),
        None,
        None,
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("false"),
        None,
        OptionScope::Invocation,
        false,
        "Continue eligible batch statements after an error",
    ),
    option(
        OptionId::Config,
        "no-config",
        None,
        None,
        Some("no-config"),
        Some("no-config"),
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("true"),
        None,
        OptionScope::Invocation,
        false,
        "Ignore the user configuration file",
    ),
    option(
        OptionId::History,
        "history",
        None,
        None,
        Some("no-history"),
        Some("no-history"),
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("true"),
        Some("history"),
        OptionScope::Editor,
        true,
        "Disable history for this process",
    ),
    option(
        OptionId::Quiet,
        "quiet",
        Some('q'),
        Some("quiet"),
        None,
        None,
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("false"),
        None,
        OptionScope::Invocation,
        false,
        "Suppress greeting and nonessential status prose",
    ),
    option(
        OptionId::Help,
        "help",
        Some('h'),
        Some("help"),
        None,
        None,
        None,
        OptionValueKind::Flag,
        &[],
        None,
        None,
        OptionScope::Invocation,
        false,
        "Print invocation help",
    ),
    option(
        OptionId::Version,
        "version",
        Some('V'),
        Some("version"),
        None,
        None,
        None,
        OptionValueKind::Flag,
        &[],
        None,
        None,
        OptionScope::Invocation,
        false,
        "Print CLI and engine version",
    ),
    option(
        OptionId::Rows,
        "rows",
        None,
        None,
        None,
        None,
        Some("ROWS"),
        OptionValueKind::PositiveInteger,
        ROWS,
        Some("20"),
        Some("rows"),
        OptionScope::Display,
        true,
        "Control the human display row limit",
    ),
    option(
        OptionId::Width,
        "width",
        None,
        None,
        None,
        None,
        Some("WIDTH"),
        OptionValueKind::PositiveInteger,
        WIDTHS,
        Some("auto"),
        Some("width"),
        OptionScope::Display,
        true,
        "Control human table width",
    ),
    option(
        OptionId::NullDisplay,
        "null-display",
        None,
        None,
        None,
        None,
        Some("MODE"),
        OptionValueKind::Choice,
        NULL_DISPLAY,
        Some("literal"),
        Some("null_display"),
        OptionScope::Display,
        true,
        "Control human NULL display",
    ),
    option(
        OptionId::Multiline,
        "multiline",
        None,
        None,
        None,
        None,
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("true"),
        Some("multiline"),
        OptionScope::Editor,
        true,
        "Control parser-aware multiline entry",
    ),
    option(
        OptionId::Highlight,
        "highlight",
        None,
        None,
        None,
        None,
        Some("WHEN"),
        OptionValueKind::Choice,
        AUTO_ON_OFF,
        Some("auto"),
        Some("highlight"),
        OptionScope::Editor,
        true,
        "Control syntax highlighting",
    ),
    option(
        OptionId::Completion,
        "completion",
        None,
        None,
        None,
        None,
        None,
        OptionValueKind::Flag,
        BOOL,
        Some("true"),
        Some("completion"),
        OptionScope::Editor,
        true,
        "Control completion",
    ),
    option(
        OptionId::HistoryLimit,
        "history-limit",
        None,
        None,
        None,
        None,
        Some("COUNT"),
        OptionValueKind::PositiveInteger,
        &[],
        Some("10000"),
        Some("history_limit"),
        OptionScope::Editor,
        false,
        "Bound persistent history entries",
    ),
];

#[allow(clippy::too_many_arguments)]
const fn option(
    id: OptionId,
    clap_id: &'static str,
    short: Option<char>,
    long: Option<&'static str>,
    negative_id: Option<&'static str>,
    negative_long: Option<&'static str>,
    value_name: Option<&'static str>,
    value_kind: OptionValueKind,
    accepted: &'static [&'static str],
    default: Option<&'static str>,
    config_key: Option<&'static str>,
    scope: OptionScope,
    interactive: bool,
    help: &'static str,
) -> OptionSpec {
    OptionSpec {
        id,
        clap_id,
        short,
        long,
        negative_id,
        negative_long,
        value_name,
        value_kind,
        accepted,
        default,
        config_key,
        scope,
        interactive,
        help,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CommandId {
    Help,
    Quit,
    Clear,
    Status,
    Graphs,
    Schema,
    Describe,
    Functions,
    Parameters,
    Parameter,
    Format,
    Timing,
    Progress,
    Rows,
    Width,
    Null,
    Multiline,
    Highlight,
    Completion,
    History,
    Read,
    Output,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompletionKind {
    None,
    HelpTopic,
    GraphObject,
    Function,
    Parameter,
    Setting,
    Path,
    OutputPath,
}

#[derive(Debug, Clone, Copy)]
pub struct CommandSpec {
    pub id: CommandId,
    pub name: &'static str,
    pub arguments: &'static str,
    pub help_topic: &'static str,
    pub completion: CompletionKind,
    pub sensitive: bool,
    pub record_history: bool,
    pub interactive_only: bool,
    pub summary: &'static str,
}

pub static COMMAND_REGISTRY: &[CommandSpec] = &[
    command(
        CommandId::Help,
        "help",
        "[topic/command]",
        "queries",
        CompletionKind::HelpTopic,
        false,
        true,
        false,
        "Show topical help or command usage",
    ),
    command(
        CommandId::Quit,
        "quit",
        "[--rollback]",
        "transactions",
        CompletionKind::None,
        false,
        true,
        false,
        "Exit the session",
    ),
    command(
        CommandId::Clear,
        "clear",
        "",
        "keys",
        CompletionKind::None,
        false,
        false,
        true,
        "Clear and redraw the terminal",
    ),
    command(
        CommandId::Status,
        "status",
        "",
        "queries",
        CompletionKind::None,
        false,
        true,
        false,
        "Show effective session and display state",
    ),
    command(
        CommandId::Graphs,
        "graphs",
        "",
        "graphs",
        CompletionKind::None,
        false,
        true,
        false,
        "List graphs and mark the selection",
    ),
    command(
        CommandId::Schema,
        "schema",
        "[graph[.object]]",
        "graphs",
        CompletionKind::GraphObject,
        false,
        true,
        false,
        "Print deterministic executable schema",
    ),
    command(
        CommandId::Describe,
        "describe",
        "<graph[.object]>",
        "graphs",
        CompletionKind::GraphObject,
        false,
        true,
        false,
        "Describe one visible object",
    ),
    command(
        CommandId::Functions,
        "functions",
        "[pattern]",
        "queries",
        CompletionKind::Function,
        false,
        true,
        false,
        "List visible functions",
    ),
    command(
        CommandId::Parameters,
        "params",
        "[--values]",
        "parameters",
        CompletionKind::Parameter,
        true,
        false,
        false,
        "List bound parameters",
    ),
    command(
        CommandId::Parameter,
        "param",
        "<name> <json> | clear <name/all>",
        "parameters",
        CompletionKind::Parameter,
        true,
        false,
        false,
        "Bind or clear parameters",
    ),
    command(
        CommandId::Format,
        "format",
        "[auto/name]",
        "formats",
        CompletionKind::Setting,
        false,
        true,
        false,
        "Show or select the output format",
    ),
    command(
        CommandId::Timing,
        "timing",
        "[on/off]",
        "formats",
        CompletionKind::Setting,
        false,
        true,
        false,
        "Control timing summaries",
    ),
    command(
        CommandId::Progress,
        "progress",
        "[auto/on/off]",
        "formats",
        CompletionKind::Setting,
        false,
        true,
        false,
        "Control live progress",
    ),
    command(
        CommandId::Rows,
        "rows",
        "[number/all/default]",
        "formats",
        CompletionKind::Setting,
        false,
        true,
        true,
        "Control displayed row count",
    ),
    command(
        CommandId::Width,
        "width",
        "[number/auto]",
        "formats",
        CompletionKind::Setting,
        false,
        true,
        false,
        "Control human table width",
    ),
    command(
        CommandId::Null,
        "null",
        "[literal/empty]",
        "formats",
        CompletionKind::Setting,
        false,
        true,
        false,
        "Control human NULL display",
    ),
    command(
        CommandId::Multiline,
        "multiline",
        "[on/off]",
        "keys",
        CompletionKind::Setting,
        false,
        true,
        true,
        "Control multiline entry",
    ),
    command(
        CommandId::Highlight,
        "highlight",
        "[auto/on/off]",
        "completion",
        CompletionKind::Setting,
        false,
        true,
        true,
        "Control syntax highlighting",
    ),
    command(
        CommandId::Completion,
        "completion",
        "[on/off]",
        "completion",
        CompletionKind::Setting,
        false,
        true,
        true,
        "Control completion and ghost text",
    ),
    command(
        CommandId::History,
        "history",
        "[show N/clear/on/off/skip]",
        "history",
        CompletionKind::Setting,
        true,
        false,
        true,
        "Inspect or control history",
    ),
    command(
        CommandId::Read,
        "read",
        "<path> [--keep-going]",
        "batch",
        CompletionKind::Path,
        false,
        true,
        false,
        "Execute a local UTF-8 command file",
    ),
    command(
        CommandId::Output,
        "output",
        "[stdout/<path> [append/replace]]",
        "formats",
        CompletionKind::OutputPath,
        false,
        true,
        false,
        "Show or change the result destination",
    ),
];

#[allow(clippy::too_many_arguments)]
const fn command(
    id: CommandId,
    name: &'static str,
    arguments: &'static str,
    help_topic: &'static str,
    completion: CompletionKind,
    sensitive: bool,
    record_history: bool,
    interactive_only: bool,
    summary: &'static str,
) -> CommandSpec {
    CommandSpec {
        id,
        name,
        arguments,
        help_topic,
        completion,
        sensitive,
        record_history,
        interactive_only,
        summary,
    }
}

pub fn command_spec(name: &str) -> Option<&'static CommandSpec> {
    COMMAND_REGISTRY
        .iter()
        .find(|spec| spec.name.eq_ignore_ascii_case(name))
}

pub fn option_spec(id: OptionId) -> &'static OptionSpec {
    OPTION_REGISTRY
        .iter()
        .find(|spec| spec.id == id)
        .expect("every option id is registered")
}

/// Construct Clap exclusively from [`OPTION_REGISTRY`].
pub fn clap_command() -> Command {
    let mut command = Command::new("koko")
        .version(koko::version())
        .disable_help_flag(true)
        .disable_version_flag(true)
        .about("Interactive and batch terminal client for the in-memory Koko graph database")
        .override_usage("koko [OPTIONS]")
        .args_conflicts_with_subcommands(true);
    for spec in OPTION_REGISTRY {
        if let Some(long) = spec.long {
            let mut argument = Arg::new(spec.clap_id).long(long).help(spec.help);
            if let Some(short) = spec.short {
                argument = argument.short(short);
            }
            argument = configure_argument(argument, spec);
            if spec.id == OptionId::Command {
                argument = argument.conflicts_with("file");
            } else if spec.id == OptionId::File {
                argument = argument.conflicts_with("command");
            }
            if let Some(negative_id) = spec.negative_id {
                argument = argument.conflicts_with(negative_id);
            }
            command = command.arg(argument);
        }
        if let (Some(id), Some(long)) = (spec.negative_id, spec.negative_long) {
            let mut argument = Arg::new(id)
                .long(long)
                .action(ArgAction::SetTrue)
                .help(spec.help);
            if spec.long.is_some() {
                argument = argument.conflicts_with(spec.clap_id);
            }
            command = command.arg(argument);
        }
    }
    command
}

fn configure_argument(mut argument: Arg, spec: &OptionSpec) -> Arg {
    if let Some(value_name) = spec.value_name {
        argument = argument.value_name(value_name);
    }
    match spec.id {
        OptionId::Help => argument.action(ArgAction::Help),
        OptionId::Version => argument.action(ArgAction::Version),
        _ => match spec.value_kind {
            OptionValueKind::Flag => argument.action(ArgAction::SetTrue),
            OptionValueKind::RepeatableText => argument.action(ArgAction::Append),
            OptionValueKind::Path => argument
                .value_parser(clap::value_parser!(std::path::PathBuf))
                .value_hint(ValueHint::FilePath),
            OptionValueKind::Choice => argument.value_parser(
                clap::builder::PossibleValuesParser::new(spec.accepted.iter().copied()),
            ),
            OptionValueKind::Text | OptionValueKind::PositiveInteger => argument,
        },
    }
}
