[package]
name = "koko-processor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
koko-common = { workspace = true }
koko-algorithm = { workspace = true }
koko-ir = { workspace = true }
koko-expr = { workspace = true }
koko-function = { workspace = true }
koko-storage = { workspace = true }
koko-catalog = { workspace = true }
koko-loader = { workspace = true }
