[package]
name = "koko"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
koko-common = { workspace = true }
koko-catalog = { workspace = true }
koko-storage = { workspace = true }
koko-parser = { workspace = true }
koko-binder = { workspace = true }
koko-ir = { workspace = true }
koko-planner = { workspace = true }
koko-expr = { workspace = true }
koko-function = { workspace = true }
koko-processor = { workspace = true }
koko-loader = { workspace = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
parquet = { workspace = true }
